name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install backend deps
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt

      - name: Run backend tests
        env:
          VECTOR_STORE: memory
          LLM_PROVIDER: stub
          DATA_DIR: ${{ github.workspace }}/data
          PYTHONPATH: ${{ github.workspace }}/backend
        run: |
          pytest -q backend/app/tests

      - name: Lint (ruff)
        run: |
          ruff check backend/app

      - name: Build Docker images
        run: |
          docker build -t policy-helper-backend ./backend
          docker build -t policy-helper-frontend ./frontend
